### ISSUE TITLE
List of Valid User Control Lights Not Found

### ISSUE THREAD

**Issue by YourInternationalTrucker** [RigsOfRods/docs.rigsofrods.org#139] opened 2020-05-24 21:39 UTC
When viewing the flares section of the truck file format page in the documents (https://docs.rigsofrods.org/vehicle-creation/fileformat-truck/#flares), it says "**Valid user defined control numbers are 0-500.**", but it doesn't show any sort of list for all of them. I do understand that 1 is CTRL+1, 2 is CTRL+2 and so on, but what about when it's say, 367? Do I just do CTRL+367? I did find a list of commands and common controls, as they are listed and explained pretty well, but when it comes to these flares, it becomes an issue. Please fix, thank you.
![image](https://user-images.githubusercontent.com/65870347/82765485-56f21a00-9de5-11ea-8e97-1d3b464728aa.png)

**Comment by CuriousMike56** [comment] 2020-05-24 22:01
Duplicate of https://github.com/RigsOfRods/rigs-of-rods/issues/2551
Once we know exactly how they work, the documentation will be updated.

**Closed by CuriousMike56** 2020-05-24 22:01 UTC
